joy_teleop:
  ros__parameters:
    joy_node:
      dev: /dev/input/js0
      deadzone: 0.01
      autorepeat_rate: 20
      coalesce_interval: 0.01

    teleop:
      default:
        type: topic
        is_default: true
        message_type: ackermann_msgs/AckermannDriveStamped
        topic_name: /input/teleop
        message_value:
          - target: drive.speed
            value: 0.0
          - target: drive.steering_angle
            value: 0.0

      human_control:
        type: topic
        message_type: ackermann_msgs/AckermannDriveStamped
        topic_name: /input/teleop
        deadman_buttons: [4]
        axis_mappings:
          - axis: 1
            target: drive.speed
            scale: 5.0
            offset: 0.0
          - axis: 2
            target: drive.steering_angle
            scale: 0.34
            offset: 0.0

      autonomous_control:
        type: topic
        message_type: std_msgs/Int8
        topic_name: /dev/null
        deadman_buttons: [5]
        message_value:
          - target: data
            value: 0
